version: "3.7"

services:
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: sitoo_test_assignment
      MYSQL_USER: sitoo
      MYSQL_PASSWORD: test
    volumes:
      - ./sql/entry.sql:/docker-entrypoint-initdb.d/entry.sql

  api:
    build: ./api
    ports:
      - 80:80
    depends_on:
      - database